using DatVeXemPhim.Models;
using System.Collections.Generic;

namespace DatVeXemPhim.Data_Access_Layer
{
    public class CinemaInitializer : System.Data.Entity.DropCreateDatabaseIfModelChanges<CinemaContext>
    {
        protected override void Seed(CinemaContext context)
        {
            var movies = new List<Movie>
            {
                new Movie {ID = 1, Title = "CHIẾN BINH SĂN PHÙ THỦY", Genre = "Hành động", ReleaseDate = new System.DateTime(2015,10,2), Length = "110 phút", Directors = "Breck Eisner", Actor = "Vin Diesel, Rose Leslie, Elijah Wood", URL = "http://lottecinemavn.com/vi-vn/phim/chien-binh-san-phu-thuy.aspx", Intro =  "Bộ phim đặt người xem vào bối cảnh thế giới bị lũng đoạn bởi sự hiện diện của tộc phù thuỷ. Cuộc chiến giữa chúng và những người thợ săn kéo dài hàng bao thế kỷ cho kết khi Kaulder (Vin Diesel) tiêu diệt được Nữ Hoàng (Julie Engelbrecht). Trước khi chết, mụ đã kịp nguyền rủa Kaulder với sự bất tử của chính mình, khiến anh mãi mãi rời xa vợ con, sống một cuộc sống cô độc kiếp này qua kiếp khác. Trở về với thế kỷ 21, Kaulder là thợ săn phù thuỷ duy nhất còn sót lại, vẫn tiếp tục tìm kiếm và tiêu diệt những sinh vật siêu nhiên chết người kia. Nhưng, anh không thể ngờ rằng, thủ lĩnh của chúng - Nữ Hoàng đã được hồi sinh và đang tìm cách trả thù loài người." },
                new Movie {ID = 2, Title = "JURASSIC WORLD", Genre = "Thần thoại", ReleaseDate = new System.DateTime(2015,10,2), Length = "120 phút", Directors = "Breck Eisner", Actor = "Vin Diesel, Rose Leslie, Elijah Wood", URL = "http://lottecinemavn.com/vi-vn/phim/chien-binh-san-phu-thuy.aspx", Intro =  "Bộ phim đặt người xem vào bối cảnh thế giới bị lũng đoạn bởi sự hiện diện của tộc phù thuỷ. Cuộc chiến giữa chúng và những người thợ săn kéo dài hàng bao thế kỷ cho kết khi Kaulder (Vin Diesel) tiêu diệt được Nữ Hoàng (Julie Engelbrecht). Trước khi chết, mụ đã kịp nguyền rủa Kaulder với sự bất tử của chính mình, khiến anh mãi mãi rời xa vợ con, sống một cuộc sống cô độc kiếp này qua kiếp khác. Trở về với thế kỷ 21, Kaulder là thợ săn phù thuỷ duy nhất còn sót lại, vẫn tiếp tục tìm kiếm và tiêu diệt những sinh vật siêu nhiên chết người kia. Nhưng, anh không thể ngờ rằng, thủ lĩnh của chúng - Nữ Hoàng đã được hồi sinh và đang tìm cách trả thù loài người." },
                new Movie {ID = 3, Title = "BƯỚC ĐI THẾ KỶ  ", Genre = "Phiêu Lưu, Hành động", ReleaseDate = new System.DateTime(2015,10,2), Length = "90 phút", Directors = "Breck Eisner", Actor = "Vin Diesel, Rose Leslie, Elijah Wood", URL = "http://lottecinemavn.com/vi-vn/phim/chien-binh-san-phu-thuy.aspx", Intro =  "Bộ phim đặt người xem vào bối cảnh thế giới bị lũng đoạn bởi sự hiện diện của tộc phù thuỷ. Cuộc chiến giữa chúng và những người thợ săn kéo dài hàng bao thế kỷ cho kết khi Kaulder (Vin Diesel) tiêu diệt được Nữ Hoàng (Julie Engelbrecht). Trước khi chết, mụ đã kịp nguyền rủa Kaulder với sự bất tử của chính mình, khiến anh mãi mãi rời xa vợ con, sống một cuộc sống cô độc kiếp này qua kiếp khác. Trở về với thế kỷ 21, Kaulder là thợ săn phù thuỷ duy nhất còn sót lại, vẫn tiếp tục tìm kiếm và tiêu diệt những sinh vật siêu nhiên chết người kia. Nhưng, anh không thể ngờ rằng, thủ lĩnh của chúng - Nữ Hoàng đã được hồi sinh và đang tìm cách trả thù loài người." },
                new Movie {ID = 4, Title = "NGƯỜI ĐÀM PHÁN", Genre = "Hình sự", ReleaseDate = new System.DateTime(2015,11,2), Length = "100 phút", Directors = "Breck Eisner", Actor = "Vin Diesel, Rose Leslie, Elijah Wood", URL = "http://lottecinemavn.com/vi-vn/phim/chien-binh-san-phu-thuy.aspx", Intro =  "Bộ phim đặt người xem vào bối cảnh thế giới bị lũng đoạn bởi sự hiện diện của tộc phù thuỷ. Cuộc chiến giữa chúng và những người thợ săn kéo dài hàng bao thế kỷ cho kết khi Kaulder (Vin Diesel) tiêu diệt được Nữ Hoàng (Julie Engelbrecht). Trước khi chết, mụ đã kịp nguyền rủa Kaulder với sự bất tử của chính mình, khiến anh mãi mãi rời xa vợ con, sống một cuộc sống cô độc kiếp này qua kiếp khác. Trở về với thế kỷ 21, Kaulder là thợ săn phù thuỷ duy nhất còn sót lại, vẫn tiếp tục tìm kiếm và tiêu diệt những sinh vật siêu nhiên chết người kia. Nhưng, anh không thể ngờ rằng, thủ lĩnh của chúng - Nữ Hoàng đã được hồi sinh và đang tìm cách trả thù loài người." },
                new Movie {ID = 5, Title = "NGƯỜI VẬN CHUYỂN", Genre = "Hành động,Thần thoại", ReleaseDate = new System.DateTime(2015,10,2), Length = "110 phút", Directors = "Breck Eisner", Actor = "Vin Diesel, Rose Leslie, Elijah Wood", URL = "http://lottecinemavn.com/vi-vn/phim/chien-binh-san-phu-thuy.aspx", Intro =  "Bộ phim đặt người xem vào bối cảnh thế giới bị lũng đoạn bởi sự hiện diện của tộc phù thuỷ. Cuộc chiến giữa chúng và những người thợ săn kéo dài hàng bao thế kỷ cho kết khi Kaulder (Vin Diesel) tiêu diệt được Nữ Hoàng (Julie Engelbrecht). Trước khi chết, mụ đã kịp nguyền rủa Kaulder với sự bất tử của chính mình, khiến anh mãi mãi rời xa vợ con, sống một cuộc sống cô độc kiếp này qua kiếp khác. Trở về với thế kỷ 21, Kaulder là thợ săn phù thuỷ duy nhất còn sót lại, vẫn tiếp tục tìm kiếm và tiêu diệt những sinh vật siêu nhiên chết người kia. Nhưng, anh không thể ngờ rằng, thủ lĩnh của chúng - Nữ Hoàng đã được hồi sinh và đang tìm cách trả thù loài người." },
                new Movie {ID = 6, Title = "NGÔI TRƯỜNG MA QUÁI", Genre = "Kinh dị", ReleaseDate = new System.DateTime(2015,10,30), Length = "99 phút", Directors = "Breck Eisner", Actor = "Park Bo-Young, Ji Wom", URL = "http://lottecinemavn.com/vi-vn/phim/chien-binh-san-phu-thuy.aspx", Intro =  "Bộ phim đặt người xem vào bối cảnh thế giới bị lũng đoạn bởi sự hiện diện của tộc phù thuỷ. Cuộc chiến giữa chúng và những người thợ săn kéo dài hàng bao thế kỷ cho kết khi Kaulder (Vin Diesel) tiêu diệt được Nữ Hoàng (Julie Engelbrecht). Trước khi chết, mụ đã kịp nguyền rủa Kaulder với sự bất tử của chính mình, khiến anh mãi mãi rời xa vợ con, sống một cuộc sống cô độc kiếp này qua kiếp khác. Trở về với thế kỷ 21, Kaulder là thợ săn phù thuỷ duy nhất còn sót lại, vẫn tiếp tục tìm kiếm và tiêu diệt những sinh vật siêu nhiên chết người kia. Nhưng, anh không thể ngờ rằng, thủ lĩnh của chúng - Nữ Hoàng đã được hồi sinh và đang tìm cách trả thù loài người." },
                new Movie {ID = 7, Title = "SỐ NHỌ", Genre = "Hài, Hành động, Thần thoại", ReleaseDate = new System.DateTime(2015,10,2), Length = "110 phút", Directors = "Breck Eisner", Actor = "Vin Diesel, Rose Leslie, Elijah Wood", URL = "http://lottecinemavn.com/vi-vn/phim/chien-binh-san-phu-thuy.aspx", Intro =  "Bộ phim đặt người xem vào bối cảnh thế giới bị lũng đoạn bởi sự hiện diện của tộc phù thuỷ. Cuộc chiến giữa chúng và những người thợ săn kéo dài hàng bao thế kỷ cho kết khi Kaulder (Vin Diesel) tiêu diệt được Nữ Hoàng (Julie Engelbrecht). Trước khi chết, mụ đã kịp nguyền rủa Kaulder với sự bất tử của chính mình, khiến anh mãi mãi rời xa vợ con, sống một cuộc sống cô độc kiếp này qua kiếp khác. Trở về với thế kỷ 21, Kaulder là thợ săn phù thuỷ duy nhất còn sót lại, vẫn tiếp tục tìm kiếm và tiêu diệt những sinh vật siêu nhiên chết người kia. Nhưng, anh không thể ngờ rằng, thủ lĩnh của chúng - Nữ Hoàng đã được hồi sinh và đang tìm cách trả thù loài người." },
                new Movie {ID = 9, Title = "MÃNG XÀ", Genre = "Hành động", ReleaseDate = new System.DateTime(2015,10,2), Length = "110 phút", Directors = "Breck Eisner", Actor = "Vin Diesel, Rose Leslie, Elijah Wood", URL = "http://lottecinemavn.com/vi-vn/phim/chien-binh-san-phu-thuy.aspx", Intro =  "Bộ phim đặt người xem vào bối cảnh thế giới bị lũng đoạn bởi sự hiện diện của tộc phù thuỷ. Cuộc chiến giữa chúng và những người thợ săn kéo dài hàng bao thế kỷ cho kết khi Kaulder (Vin Diesel) tiêu diệt được Nữ Hoàng (Julie Engelbrecht). Trước khi chết, mụ đã kịp nguyền rủa Kaulder với sự bất tử của chính mình, khiến anh mãi mãi rời xa vợ con, sống một cuộc sống cô độc kiếp này qua kiếp khác. Trở về với thế kỷ 21, Kaulder là thợ săn phù thuỷ duy nhất còn sót lại, vẫn tiếp tục tìm kiếm và tiêu diệt những sinh vật siêu nhiên chết người kia. Nhưng, anh không thể ngờ rằng, thủ lĩnh của chúng - Nữ Hoàng đã được hồi sinh và đang tìm cách trả thù loài người." },
                new Movie {ID = 10, Title = "LỜI NGUYỀN CON ĐẦM BÍCH", Genre = "Hành động", ReleaseDate = new System.DateTime(2015,10,2), Length = "110 phút", Directors = "Breck Eisner", Actor = "Vin Diesel, Rose Leslie, Elijah Wood", URL = "http://lottecinemavn.com/vi-vn/phim/chien-binh-san-phu-thuy.aspx", Intro =  "Bộ phim đặt người xem vào bối cảnh thế giới bị lũng đoạn bởi sự hiện diện của tộc phù thuỷ. Cuộc chiến giữa chúng và những người thợ săn kéo dài hàng bao thế kỷ cho kết khi Kaulder (Vin Diesel) tiêu diệt được Nữ Hoàng (Julie Engelbrecht). Trước khi chết, mụ đã kịp nguyền rủa Kaulder với sự bất tử của chính mình, khiến anh mãi mãi rời xa vợ con, sống một cuộc sống cô độc kiếp này qua kiếp khác. Trở về với thế kỷ 21, Kaulder là thợ săn phù thuỷ duy nhất còn sót lại, vẫn tiếp tục tìm kiếm và tiêu diệt những sinh vật siêu nhiên chết người kia. Nhưng, anh không thể ngờ rằng, thủ lĩnh của chúng - Nữ Hoàng đã được hồi sinh và đang tìm cách trả thù loài người." },
                new Movie {ID = 11, Title = "LẠC LỐI Ở HỒNG KÔNG", Genre = "Hành động", ReleaseDate = new System.DateTime(2015,10,2), Length = "110 phút", Directors = "Breck Eisner", Actor = "Vin Diesel, Rose Leslie, Elijah Wood", URL = "http://lottecinemavn.com/vi-vn/phim/chien-binh-san-phu-thuy.aspx", Intro =  "Bộ phim đặt người xem vào bối cảnh thế giới bị lũng đoạn bởi sự hiện diện của tộc phù thuỷ. Cuộc chiến giữa chúng và những người thợ săn kéo dài hàng bao thế kỷ cho kết khi Kaulder (Vin Diesel) tiêu diệt được Nữ Hoàng (Julie Engelbrecht). Trước khi chết, mụ đã kịp nguyền rủa Kaulder với sự bất tử của chính mình, khiến anh mãi mãi rời xa vợ con, sống một cuộc sống cô độc kiếp này qua kiếp khác. Trở về với thế kỷ 21, Kaulder là thợ săn phù thuỷ duy nhất còn sót lại, vẫn tiếp tục tìm kiếm và tiêu diệt những sinh vật siêu nhiên chết người kia. Nhưng, anh không thể ngờ rằng, thủ lĩnh của chúng - Nữ Hoàng đã được hồi sinh và đang tìm cách trả thù loài người." },
                new Movie {ID = 12, Title = "TRUY HỒI KÝ ỨC", Genre = "Hình sự, trinh thám", ReleaseDate = new System.DateTime(2015,10,2), Length = "110 phút", Directors = "Breck Eisner", Actor = "Vin Diesel, Rose Leslie, Elijah Wood", URL = "http://lottecinemavn.com/vi-vn/phim/chien-binh-san-phu-thuy.aspx", Intro =  "Bộ phim đặt người xem vào bối cảnh thế giới bị lũng đoạn bởi sự hiện diện của tộc phù thuỷ. Cuộc chiến giữa chúng và những người thợ săn kéo dài hàng bao thế kỷ cho kết khi Kaulder (Vin Diesel) tiêu diệt được Nữ Hoàng (Julie Engelbrecht). Trước khi chết, mụ đã kịp nguyền rủa Kaulder với sự bất tử của chính mình, khiến anh mãi mãi rời xa vợ con, sống một cuộc sống cô độc kiếp này qua kiếp khác. Trở về với thế kỷ 21, Kaulder là thợ săn phù thuỷ duy nhất còn sót lại, vẫn tiếp tục tìm kiếm và tiêu diệt những sinh vật siêu nhiên chết người kia. Nhưng, anh không thể ngờ rằng, thủ lĩnh của chúng - Nữ Hoàng đã được hồi sinh và đang tìm cách trả thù loài người." },
            };
            movies.ForEach(s => context.Movies.Add(s));
            context.SaveChanges();
        }

    }
}
